/* global module:false */
module.exports = function( grunt ){

  grunt.registerTask( 'treeview', function(){

    var treeJSON,
        jadeVars;

    // register a task te delete the tree file once its used
    grunt.registerTask( 'cleanTreeJSON', 'remove the tree.json file generated by grunt-tree', function(){
      grunt.file.delete( 'tree.json' );
    } );

    grunt.registerTask('readJSON', "get the treeview JSON", function(){
      treeJSON = grunt.file.readJSON("tree.json");

      jadeVars = grunt.util._.extend({
        projectName: "<%= package.title %>",
        tree: treeJSON,
        treeFile: "tree"
      }, grunt.file.readJSON('pages/vars.json') );
      grunt.config.set('jade.tree', {
        files: {
          "<%= build %>/tree.html": grunt.file.exists("pages/tree.jade") ? "pages/tree.jade" : "tree.jade"
        },
        options: {
          data: jadeVars,
          pretty: true,
          selfClose: true,
          compileDebug: false
        }
      });

    });

    grunt.task.run( [
      'tree',
      'readJSON',
      'jade:tree',
      'cleanTreeJSON'
    ] );

  });

};
